### ISSUE TITLE
rss feed url link

### ISSUE THREAD

**Issue by Pat-Lafon** [Kobzol/kobzol.github.io#21]
https://github.com/Kobzol/kobzol.github.io/blob/6a652d3d89397bb5b8cb23d0b3a0b633aeefea73/_config.yml#L26

Hello, You might be interested to update your config file with the url of your website/blog. I was looking to read your new post, "Adding runtime benchmarks to the Rust compiler benchmark suite" but it has a broken link to the post like `/rust/rustc/2023/09/23/rustc-runtime-benchmarks.html` . The link to your blogs main page is just `/`.

This isn't always an issue since some rss feeds contain the whole post so they don't necessarily need the link.

Not a huge issue, just a QoL change if you are interested

**Comment by Kobzol** [comment]
That's weird, I could swear that the RSS has been working before. Anyway, should be fixed now. Thank you! :)
